apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: AKIAIOSFODNN7EXAMPLE
  secretAccessKey: mysecretkey123456
  endpoint: http://10.226.160.13:9000
  region: ""
