apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-streaming
  namespace: streaming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-streaming     # 👈 绑定 PV
  storageClassName: ""         # 👈 必须为空（静态绑定）
  volumeMode: Filesystem
